### ISSUE TITLE
Clean up boilerplate React Native

### ISSUE THREAD

**Issue by markspanbroek** [philips-software/cogito#125]
- [x] Check whether BUCK and Gradle are both needed
- [x] .flowconfig really needed?

Etc..

**Comment by Hacklor** [comment]
I've looked at Buck and removed the `.buckconfig` file. It seems to me that it is a smart way of Facebook to promote their own build tool. However it needs to be installed separately. So it was not even active on my Macbook.

See branch `investigate-tools`

**Comment by Hacklor** [comment]
Flow is a static type checker for Javascript. It uses annotations in the code. It requires the dependency `babel-preset-flow` which we do not have in our `package.json`. This means that the config is not required and can be removed.

**Comment by markspanbroek** [comment]
Closed because #132 was merged.
