### ISSUE TITLE
Make cogito use web sockets with web3/truffle

### ISSUE THREAD

**Issue by marcinczenko** [philips-software/cogito#37]
Client apps receive an instance of web3 via `@cogitojs/cogito` package. This is where we use `Web3.providers.HttpProvider` to get a reference to a Web3 provider.

According to this thread: https://github.com/trufflesuite/ganache-cli/issues/257#issuecomment-357874959 web sockets should work with new ganache releases. Also zeit (where we deploy our ganache network for secure transfer) seem to support web-sockets.

Apart from having potential of a much more elegant solution, this should also get rid of the polling, which may cause the system to get banned on some corporate networks.

**Comment by markspanbroek** [comment]
I was under the impression that Cogito only wraps the Web3 provider that is given to it. If you give it a Web3 provider that uses websockets, should it just work?

**Comment by marcinczenko** [comment]
I think that the cogito web3/contracts chain is not really clean. I propose a refactoring in #43.

**Comment by marcinczenko** [comment]
I am closing this as this issue has been covered by #42.
