### ISSUE TITLE
Unencrypted CodeClimate token in repo

### ISSUE THREAD

**Issue by loafoe** [philips-software/cogito#38]
The CC key is exposed in the repo:

https://github.com/philips-software/cogito/blob/7042d9a687f12dde77489a247b4d45df4ed3a698/.travis.yml#L7

Details on how to fix: https://docs.travis-ci.com/user/environment-variables#encrypting-environment-variables
As encryption is tied to the repo only repo owners can fix this so cannot create a PR :)

**Comment by JeroenKnoops** [comment]
I will fix this. Thanks
