### ISSUE TITLE
Linking to settings when passcode is turned off

### ISSUE THREAD

**Issue by Hacklor** [philips-software/cogito#75]
Creating identity when the passcode is off results in an alert box with a warning. This is correct.

It would be nice to have a settings button included that directs the user to the passcode settings screen where the change needs to be made. It would be even nicer to have a "back to cogito" option on the top left that directs the user back to the cogito screen to continue.

![img_0001](https://user-images.githubusercontent.com/3730478/53158450-e5189880-35c3-11e9-8b62-3554a28d5331.PNG)

**Comment by markspanbroek** [comment]
Apparently Apple [doesn't allow deep linking](https://forums.developer.apple.com/thread/75110) into the settings in their app review process. You can only [open the app settings](https://developer.apple.com/documentation/uikit/uiapplicationopensettingsurlstring), but this does not include the passcode setting.
