### ISSUE TITLE
Identity: Feedback when scanning QR code

### ISSUE THREAD

**Issue by markspanbroek** [philips-software/cogito#76]
Reported by @Hacklor:

When scanning the QR code with the mobile device there is no clear indication that the scanning was successful.

It does close the Camera Window on the app, but I cannot tell if it is because it was scanned or because an error occured. There is also no message on the web-app.

Suggestion: It would be nice to have a message on the phone saying "Successfully scanned" and that the QR code window closes in the web-app.

(This probably requires the work in #72 to be completed)

**Comment by Hacklor** [comment]
Because of recent changes the `Done` button has been removed and the dialog will close automatically when reading the QR code has been successful. This already gives an indirect message to the user that it worked as expected.

Closing
