### ISSUE TITLE
[demo-app]: Contracts; Amount not updated

### ISSUE THREAD

**Issue by Hacklor** [philips-software/cogito#80]
When adding and signing an amount is successful, it doesn't automatically update the amount show in the demo app.

Suggestion:
Update the current amount

**Comment by markspanbroek** [comment]
When I run this scenario, it updates the amount automatically. Are there any error in the browser console?

**Comment by markspanbroek** [comment]
Closing. Feel free to reopen when there is a reproducible scenario.
