### ISSUE TITLE
Port to Android

### ISSUE THREAD

**Issue by markspanbroek** [philips-software/cogito#99]
Ensure that the Cogito mobile app also works on Android. Either by porting the existing iOS code to Android code, or by converting the iOS code to React Native.

**Comment by markspanbroek** [comment]
We've evaluated [Expo](https://expo.io), plain [React Native](https://facebook.github.io/react-native/), React Native with ClojureScript, and a fully native app with Kotlin.

We've decided to go for plain React Native.

**Comment by Hacklor** [comment]
I suggest to create an epic with multiple stories with functional descriptions for each feature / functionality of the new mobile application.

This way everyone has an overview of what needs to be done to create the application. Having one story / issue to cover everything is too large imo.

**Comment by markspanbroek** [comment]
Closing; the React Native development work has been split into several new issues under the [mobile label](https://github.com/philips-software/cogito/labels/mobile).
